package handlers

import (
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
)

// ExportFlowReport generates a structured Markdown report for a completed flow,
// including flow metadata, timeline, tool actions, and findings.
func ExportFlowReport(d *Deps) gin.HandlerFunc {
	return func(c *gin.Context) {
		flowID := c.Param("id")

		flow := checkFlowAccess(c, d, flowID)
		if flow == nil {
			return
		}

		// Fetch actions (tool calls) for this flow
		var actions []map[string]interface{}
		d.DB.Raw(`
			SELECT a.tool_name, a.input, a.output, a.success, a.duration_ms, a.created_at, t.agent_type
			FROM actions a
			JOIN tasks t ON t.id = a.task_id
			WHERE t.flow_id = ? AND a.type = 'tool_call'
			ORDER BY a.created_at ASC
		`, flowID).Scan(&actions)

		// Fetch artifacts (findings) for this flow
		var artifacts []map[string]interface{}
		d.DB.Raw(`
			SELECT ar.name, ar.type, ar.value, ar.severity, ar.created_at
			FROM artifacts ar
			JOIN actions a ON a.id = ar.action_id
			JOIN tasks t ON t.id = a.task_id
			WHERE t.flow_id = ?
			ORDER BY
				CASE ar.severity
					WHEN 'critical' THEN 0
					WHEN 'high' THEN 1
					WHEN 'medium' THEN 2
					WHEN 'low' THEN 3
					WHEN 'info' THEN 4
					ELSE 5
				END ASC,
				ar.created_at ASC
		`, flowID).Scan(&artifacts)

		// Build Markdown report
		var sb strings.Builder

		sb.WriteString("# PENTAGRON — Penetration Test Report\n\n")
		sb.WriteString(fmt.Sprintf("**Generated:** %s\n\n", time.Now().UTC().Format(time.RFC3339)))
		sb.WriteString("---\n\n")

		// Flow metadata
		sb.WriteString("## Engagement Summary\n\n")
		sb.WriteString(fmt.Sprintf("| Field | Value |\n"))
		sb.WriteString(fmt.Sprintf("|-------|-------|\n"))
		sb.WriteString(fmt.Sprintf("| **Flow** | %v |\n", flow["name"]))
		sb.WriteString(fmt.Sprintf("| **Status** | %v |\n", flow["status"]))
		sb.WriteString(fmt.Sprintf("| **Phase** | %v |\n", flow["phase"]))
		sb.WriteString(fmt.Sprintf("| **Attack Path** | %v |\n", flow["attack_path"]))
		sb.WriteString(fmt.Sprintf("| **Objective** | %v |\n", flow["objective"]))
		sb.WriteString(fmt.Sprintf("| **Started** | %v |\n", flow["started_at"]))
		sb.WriteString(fmt.Sprintf("| **Completed** | %v |\n", flow["completed_at"]))
		sb.WriteString("\n")

		// Findings
		if len(artifacts) > 0 {
			sb.WriteString("## Findings\n\n")
			sb.WriteString("| Severity | Type | Name | Description |\n")
			sb.WriteString("|----------|------|------|-------------|\n")
			for _, a := range artifacts {
				severity := strings.ToUpper(fmt.Sprintf("%v", a["severity"]))
				value := fmt.Sprintf("%v", a["value"])
				if len(value) > 100 {
					value = value[:100] + "..."
				}
				sb.WriteString(fmt.Sprintf("| %s | %v | %v | %s |\n",
					severity, a["type"], a["name"], value))
			}
			sb.WriteString("\n")
		} else {
			sb.WriteString("## Findings\n\nNo findings recorded for this engagement.\n\n")
		}

		// Tool execution timeline
		if len(actions) > 0 {
			sb.WriteString("## Tool Execution Timeline\n\n")
			sb.WriteString("| Time | Agent | Tool | Success | Duration |\n")
			sb.WriteString("|------|-------|------|---------|----------|\n")
			for _, a := range actions {
				success := "PASS"
				if s, ok := a["success"].(bool); ok && !s {
					success = "FAIL"
				}
				sb.WriteString(fmt.Sprintf("| %v | %v | %v | %s | %vms |\n",
					a["created_at"], a["agent_type"], a["tool_name"], success, a["duration_ms"]))
			}
			sb.WriteString("\n")
		}

		sb.WriteString("---\n\n")
		sb.WriteString("*Generated by PENTAGRON // Mission Control*\n")

		report := sb.String()

		format := c.DefaultQuery("format", "markdown")
		if format == "json" {
			c.JSON(http.StatusOK, gin.H{
				"flow":      flow,
				"findings":  artifacts,
				"actions":   actions,
				"markdown":  report,
			})
			return
		}

		// Return as downloadable Markdown
		flowName := fmt.Sprintf("%v", flow["name"])
		c.Header("Content-Disposition", fmt.Sprintf("attachment; filename=pentagron-report-%s.md", flowName))
		c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(report))
	}
}
