package handlers

import (
	"bytes"
	"fmt"
	"net/http"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/jung-kurt/gofpdf"
)

// severityColour maps a severity string to an RGB colour for PDF rendering.
func severityColour(sev string) (r, g, b int) { //nolint:unparam
	switch strings.ToLower(sev) {
	case "critical":
		return 180, 0, 0
	case "high":
		return 220, 80, 0
	case "medium":
		return 200, 160, 0
	case "low":
		return 60, 130, 60
	default:
		return 100, 100, 100
	}
}

// buildMarkdown constructs the Markdown report string from flow data.
func buildMarkdown(flow map[string]any, artifacts, actions []map[string]any) string {
	var sb strings.Builder
	sb.WriteString("# PENTAGRON — Penetration Test Report\n\n")
	sb.WriteString("**Generated:** " + time.Now().UTC().Format(time.RFC3339) + "\n\n")
	sb.WriteString("---\n\n")

	sb.WriteString("## Engagement Summary\n\n")
	sb.WriteString("| Field | Value |\n|-------|-------|\n")
	sb.WriteString(fmt.Sprintf("| **Flow** | %v |\n", flow["name"]))
	sb.WriteString(fmt.Sprintf("| **Status** | %v |\n", flow["status"]))
	sb.WriteString(fmt.Sprintf("| **Phase** | %v |\n", flow["phase"]))
	sb.WriteString(fmt.Sprintf("| **Attack Path** | %v |\n", flow["attack_path"]))
	sb.WriteString(fmt.Sprintf("| **Objective** | %v |\n", flow["objective"]))
	sb.WriteString(fmt.Sprintf("| **Started** | %v |\n", flow["started_at"]))
	sb.WriteString(fmt.Sprintf("| **Completed** | %v |\n", flow["completed_at"]))
	sb.WriteString("\n")

	if len(artifacts) > 0 {
		sb.WriteString("## Findings\n\n")
		sb.WriteString("| Severity | Type | Name | Description |\n|----------|------|------|-------------|\n")
		for _, a := range artifacts {
			sev := strings.ToUpper(fmt.Sprintf("%v", a["severity"]))
			val := fmt.Sprintf("%v", a["value"])
			if len(val) > 100 {
				val = val[:100] + "..."
			}
			sb.WriteString(fmt.Sprintf("| %s | %v | %v | %s |\n", sev, a["type"], a["name"], val))
		}
		sb.WriteString("\n")
	} else {
		sb.WriteString("## Findings\n\nNo findings recorded for this engagement.\n\n")
	}

	if len(actions) > 0 {
		sb.WriteString("## Tool Execution Timeline\n\n")
		sb.WriteString("| Time | Agent | Tool | Success | Duration |\n|------|-------|------|---------|----------|\n")
		for _, a := range actions {
			ok := "PASS"
			if s, valid := a["success"].(bool); valid && !s {
				ok = "FAIL"
			}
			sb.WriteString(fmt.Sprintf("| %v | %v | %v | %s | %vms |\n",
				a["created_at"], a["agent_type"], a["tool_name"], ok, a["duration_ms"]))
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n\n*Generated by PENTAGRON // Mission Control*\n")
	return sb.String()
}

// buildPDF generates a branded PDF report and returns the raw bytes.
func buildPDF(flow map[string]any, artifacts, actions []map[string]any) ([]byte, error) {
	pdf := gofpdf.New("P", "mm", "A4", "")
	pdf.SetMargins(20, 20, 20)
	pdf.SetAutoPageBreak(true, 20)
	pdf.AddPage()

	// ── Header bar ──────────────────────────────────────────────────────────
	pdf.SetFillColor(10, 10, 10)
	pdf.Rect(0, 0, 210, 28, "F")
	pdf.SetTextColor(16, 185, 129) // emerald
	pdf.SetFont("Helvetica", "B", 18)
	pdf.SetXY(20, 8)
	pdf.Cell(0, 10, "PENTAGRON")
	pdf.SetTextColor(200, 200, 200)
	pdf.SetFont("Helvetica", "", 10)
	pdf.SetXY(20, 18)
	pdf.Cell(0, 6, "Penetration Test Report  //  Mission Control")

	pdf.SetTextColor(120, 120, 120)
	pdf.SetFont("Helvetica", "", 8)
	pdf.SetXY(120, 20)
	pdf.Cell(0, 6, fmt.Sprintf("Generated: %s", time.Now().UTC().Format("2006-01-02 15:04 UTC")))

	pdf.SetY(36)

	// ── Engagement Summary ──────────────────────────────────────────────────
	pdf.SetTextColor(16, 185, 129)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.Cell(0, 8, "Engagement Summary")
	pdf.Ln(10)

	rows := [][]string{
		{"Flow", fmt.Sprintf("%v", flow["name"])},
		{"Status", fmt.Sprintf("%v", flow["status"])},
		{"Phase", fmt.Sprintf("%v", flow["phase"])},
		{"Attack Path", fmt.Sprintf("%v", flow["attack_path"])},
		{"Objective", fmt.Sprintf("%v", flow["objective"])},
		{"Started", fmt.Sprintf("%v", flow["started_at"])},
		{"Completed", fmt.Sprintf("%v", flow["completed_at"])},
	}
	pdf.SetFont("Helvetica", "", 9)
	for i, row := range rows {
		if i%2 == 0 {
			pdf.SetFillColor(22, 27, 34)
		} else {
			pdf.SetFillColor(30, 37, 46)
		}
		pdf.SetTextColor(180, 180, 180)
		pdf.CellFormat(50, 6, row[0], "", 0, "L", true, 0, "")
		pdf.SetTextColor(230, 230, 230)
		pdf.CellFormat(120, 6, row[1], "", 1, "L", true, 0, "")
	}
	pdf.Ln(8)

	// ── Findings ─────────────────────────────────────────────────────────────
	pdf.SetTextColor(16, 185, 129)
	pdf.SetFont("Helvetica", "B", 13)
	pdf.Cell(0, 8, fmt.Sprintf("Findings  (%d)", len(artifacts)))
	pdf.Ln(10)

	if len(artifacts) == 0 {
		pdf.SetTextColor(120, 120, 120)
		pdf.SetFont("Helvetica", "I", 9)
		pdf.Cell(0, 6, "No findings recorded for this engagement.")
		pdf.Ln(10)
	} else {
		// Table header
		pdf.SetFillColor(16, 185, 129)
		pdf.SetTextColor(10, 10, 10)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.CellFormat(22, 6, "SEVERITY", "1", 0, "C", true, 0, "")
		pdf.CellFormat(28, 6, "TYPE", "1", 0, "C", true, 0, "")
		pdf.CellFormat(45, 6, "NAME", "1", 0, "C", true, 0, "")
		pdf.CellFormat(75, 6, "DESCRIPTION", "1", 1, "C", true, 0, "")

		pdf.SetFont("Helvetica", "", 8)
		for i, a := range artifacts {
			sev := fmt.Sprintf("%v", a["severity"])
			val := fmt.Sprintf("%v", a["value"])
			if len(val) > 80 {
				val = val[:80] + "…"
			}
			if i%2 == 0 {
				pdf.SetFillColor(22, 27, 34)
			} else {
				pdf.SetFillColor(30, 37, 46)
			}
			r, g, b := severityColour(sev)
			pdf.SetTextColor(r, g, b)
			pdf.CellFormat(22, 5, strings.ToUpper(sev), "1", 0, "C", true, 0, "")
			pdf.SetTextColor(200, 200, 200)
			pdf.CellFormat(28, 5, fmt.Sprintf("%v", a["type"]), "1", 0, "L", true, 0, "")
			pdf.CellFormat(45, 5, fmt.Sprintf("%v", a["name"]), "1", 0, "L", true, 0, "")
			pdf.CellFormat(75, 5, val, "1", 1, "L", true, 0, "")
		}
		pdf.Ln(8)
	}

	// ── Tool Timeline ────────────────────────────────────────────────────────
	if len(actions) > 0 {
		pdf.SetTextColor(16, 185, 129)
		pdf.SetFont("Helvetica", "B", 13)
		pdf.Cell(0, 8, fmt.Sprintf("Tool Execution Timeline  (%d calls)", len(actions)))
		pdf.Ln(10)

		pdf.SetFillColor(16, 185, 129)
		pdf.SetTextColor(10, 10, 10)
		pdf.SetFont("Helvetica", "B", 9)
		pdf.CellFormat(42, 6, "TIMESTAMP", "1", 0, "C", true, 0, "")
		pdf.CellFormat(28, 6, "AGENT", "1", 0, "C", true, 0, "")
		pdf.CellFormat(40, 6, "TOOL", "1", 0, "C", true, 0, "")
		pdf.CellFormat(18, 6, "RESULT", "1", 0, "C", true, 0, "")
		pdf.CellFormat(22, 6, "DURATION", "1", 1, "C", true, 0, "")

		pdf.SetFont("Helvetica", "", 8)
		for i, a := range actions {
			ok := "PASS"
			okColour := [3]int{60, 130, 60}
			if s, valid := a["success"].(bool); valid && !s {
				ok = "FAIL"
				okColour = [3]int{180, 0, 0}
			}
			if i%2 == 0 {
				pdf.SetFillColor(22, 27, 34)
			} else {
				pdf.SetFillColor(30, 37, 46)
			}
			ts := fmt.Sprintf("%v", a["created_at"])
			if len(ts) > 19 {
				ts = ts[:19]
			}
			pdf.SetTextColor(200, 200, 200)
			pdf.CellFormat(42, 5, ts, "1", 0, "L", true, 0, "")
			pdf.CellFormat(28, 5, fmt.Sprintf("%v", a["agent_type"]), "1", 0, "L", true, 0, "")
			pdf.CellFormat(40, 5, fmt.Sprintf("%v", a["tool_name"]), "1", 0, "L", true, 0, "")
			pdf.SetTextColor(okColour[0], okColour[1], okColour[2])
			pdf.CellFormat(18, 5, ok, "1", 0, "C", true, 0, "")
			pdf.SetTextColor(200, 200, 200)
			pdf.CellFormat(22, 5, fmt.Sprintf("%vms", a["duration_ms"]), "1", 1, "C", true, 0, "")
		}
	}

	// ── Footer ───────────────────────────────────────────────────────────────
	pdf.SetY(-15)
	pdf.SetFillColor(10, 10, 10)
	pdf.Rect(0, pdf.GetY(), 210, 15, "F")
	pdf.SetTextColor(80, 80, 80)
	pdf.SetFont("Helvetica", "", 7)
	pdf.CellFormat(170, 6, "PENTAGRON // Mission Control — Confidential — Authorised Use Only", "", 0, "L", false, 0, "")
	pdf.CellFormat(0, 6, fmt.Sprintf("Page %d", pdf.PageNo()), "", 0, "R", false, 0, "")

	var buf bytes.Buffer
	if err := pdf.Output(&buf); err != nil {
		return nil, fmt.Errorf("pdf output: %w", err)
	}
	return buf.Bytes(), nil
}

// ExportFlowReport generates a structured report for a completed flow.
// Query ?format=pdf for PDF, ?format=json for structured JSON, default is Markdown.
func ExportFlowReport(d *Deps) gin.HandlerFunc {
	return func(c *gin.Context) {
		flowID := c.Param("id")

		flow := checkFlowAccess(c, d, flowID)
		if flow == nil {
			return
		}

		// Fetch actions (tool calls) for this flow
		var actions []map[string]interface{}
		d.DB.Raw(`
			SELECT a.tool_name, a.input, a.output, a.success, a.duration_ms, a.created_at, t.agent_type
			FROM actions a
			JOIN tasks t ON t.id = a.task_id
			WHERE t.flow_id = ? AND a.type = 'tool_call'
			ORDER BY a.created_at ASC
		`, flowID).Scan(&actions)

		// Fetch artifacts (findings) for this flow
		var artifacts []map[string]interface{}
		d.DB.Raw(`
			SELECT ar.name, ar.type, ar.value, ar.severity, ar.created_at
			FROM artifacts ar
			JOIN actions a ON a.id = ar.action_id
			JOIN tasks t ON t.id = a.task_id
			WHERE t.flow_id = ?
			ORDER BY
				CASE ar.severity
					WHEN 'critical' THEN 0
					WHEN 'high' THEN 1
					WHEN 'medium' THEN 2
					WHEN 'low' THEN 3
					WHEN 'info' THEN 4
					ELSE 5
				END ASC,
				ar.created_at ASC
		`, flowID).Scan(&artifacts)

		flowName := fmt.Sprintf("%v", flow["name"])
		format := c.DefaultQuery("format", "markdown")

		switch format {
		case "pdf":
			pdfBytes, err := buildPDF(flow, artifacts, actions)
			if err != nil {
				c.JSON(http.StatusInternalServerError, gin.H{"error": "pdf generation failed"})
				return
			}
			c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="pentagron-report-%s.pdf"`, flowName))
			c.Data(http.StatusOK, "application/pdf", pdfBytes)

		case "json":
			c.JSON(http.StatusOK, gin.H{
				"flow":     flow,
				"findings": artifacts,
				"actions":  actions,
				"markdown": buildMarkdown(flow, artifacts, actions),
			})

		default:
			md := buildMarkdown(flow, artifacts, actions)
			c.Header("Content-Disposition", fmt.Sprintf(`attachment; filename="pentagron-report-%s.md"`, flowName))
			c.Data(http.StatusOK, "text/markdown; charset=utf-8", []byte(md))
		}
	}
}
